import { Inter } from "next/font/google";
import QueryProviders from "./react-query-provider";
import "@/styles/globals.css";
import "@/styles/globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "The Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: JSX.Element }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProviders>{children}</QueryProviders>
      </body>
    </html>
  );
}
